### ISSUE TITLE
Testing Error

### ISSUE THREAD

**Issue by qiaott** [ypxie/HDGan#9]
Hi, I have encountered a problem, I wanted to try the pre-trained model, but when I run the **sh test_birds.sh** for birds, I had this problem (shown below), I was quite confused, because I think I downloaded all files and models and didn't change the code or anything. can you take a look? Thanks for your attention, hope to get your reply soon. 

Traceback (most recent call last):
  File "test_worker.py", line 70, in <module>
    test_gans(dataset, model_root, model_name, save_folder, netG, args)
  File "../../HDGan/HDGan_test.py", line 99, in test_gans
    print('netG output:', netG(this_test_embeddings, testing_z[0:this_batch_size]))
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../../HDGan/models/hd_networks.py", line 253, in forward
    x = self.vec_to_tensor(text)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../../HDGan/models/hd_networks.py", line 165, in forward
    output = self.out(inputs)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 45, in forward
    self._check_input_dim(input)
  File "/nethome/xshen/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 193, in _check_input_dim
    .format(input.dim()))
ValueError: expected 4D input (got 2D input)

**Comment by ypxie** [comment]
It maybe due to the version differences of pytorch. I have updated the code. Please let me know if you have further issues. Thanks~

**Comment by qiaott** [comment]
Thanks for your help!!! now it worked!! It has troubled me for 2 days.....
And you were right, my pytorch was 0.4.0, because it is updated automatically by conda when I was installing torchvision. I also suspected that it might because of the version of pytorch.
I have more question, how long does it cost for training the model?

**Comment by ypxie** [comment]
you're welcome. Usually, it takes 2-3 days on a 1080 Ti to finish 600 epoches on birds dataset.
